### ISSUE TITLE
How can I delegate to another handler?

### ISSUE THREAD

**Issue by TechnikEmpire** [davidfowl/MultiProtocolAspNetCore#1]
Thanks for posting this. I realize that posting questions in bug tickets is generally faux pas but since this is an example and you're the expert, I wanted to ask!

In your custom connection handler, is it possible to shift the connection and/or connection context to a different handler? For example, if I have a custom handler that does a peek read on the incoming connection, and determines that the incoming connection is HTTP, can I just give the connection back to Kestrel's default HTTP handling system?

Thanks for your time.

**Comment by davidfowl** [comment]
Yes, the UseConnectionHandler is terminal but there are other overloads on `IConnectionBuilder` that take the next handler. We should probably add a `UseConnectionMiddleware`  that mirrors what middleware in ASP.NET Core today looks like.

**Comment by TechnikEmpire** [comment]
Ah I see, so presently this is not possible in say 2.1.x? I'm looking at the code and it see your remarks about it being terminal mirrored there, and it looks like `Next` is ignored/unused.

**Comment by TechnikEmpire** [comment]
Nevermind, I see what you meant! It is possible, you use the other overloads and if you want to delegate to the default http pipeline, you simply rewind the transport pipe and invoke the next func. Thank you!
