### ISSUE TITLE
How to get a connection and send message 

### ISSUE THREAD

**Issue by swpuzhang** [davidfowl/MultiProtocolAspNetCore#3]
I want to get the socket of the connection and send message to client but ConnectionContext can't do this so i convert connection to SocketConnection, but SocketConnection is a sealed class, so I can only convert it to TransportConnection.
how to get the socket and send message to client

 public override async Task OnConnectedAsync(ConnectionContext connection)
        {
            TransportConnection sockConn = connection as TransportConnection;
            //SocketConnection sockConn = connection SocketConnection

**Comment by Sodoshi** [comment]
You can send a message with:
sockConn .Transport.Output.WriteAsync() ?

**Comment by swpuzhang** [comment]
connection.Transport.Output  and connection.Transport.Input is a pair of receive pipe, They are used to deal with receive data. not send data

**Comment by Sodoshi** [comment]
No, Input receives data, Output sends. The example is an echo server which sends the data back to the connected socket.

**Comment by swpuzhang** [comment]
ok. thank you
